### ISSUE TITLE
unavailable c5n.18xlarge compute instances 

### ISSUE THREAD

**Issue by tarankalra1** [JiaweiZhuang/cloud-gchp-paper#8]
Jiawei, 

We had earlier setup our model on the cloud using your instructions. Lately, we have had little to no success in accessing compute instances and are unable to start our job. 

We had spot instance configured in our configuration file and were testing with that. Then we commented those lines and even then can't have the compute instances fired up. 

```
## lines from our pcluster configure file
placement_group = DYNAMIC
placement = cluster # Added this based on Jiawei blog

#cluster_type = spot
#spot_bid_percentage = 80
```

Your paper mentioned that you never had issues accessing these instances. Is there something obvious that we are missing and can add in our configure file to get access to the c5n.18x large ?

**Comment by rsignell-usgs** [comment]
@tarankalra-usgs , can you please explain how you resolved this?
